server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
#    url: jdbc:postgresql://45.138.162.61:5432/customer
    url: jdbc:postgresql://localhost:5432/customer
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false